
CREATE DATABASE QL_CUAHANGDIENTHOAI
GO

USE QL_CUAHANGDIENTHOAI
GO

CREATE TABLE KHACHHANG
(
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH NVARCHAR(10),
    DIACHI NVARCHAR(255),
    SDT VARCHAR(11) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    NGAYTAO DATETIME DEFAULT GETDATE(),
    TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE NHANVIEN
(
    MANV INT IDENTITY(1,1) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH NVARCHAR(10),
    DIACHI NVARCHAR(255),
    SDT VARCHAR(11) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CHUCVU NVARCHAR(50),
    NGAYTAO DATETIME DEFAULT GETDATE(),
    TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE TAIKHOAN
(
    MATK INT IDENTITY(1,1) PRIMARY KEY,
    TENDANGNHAP VARCHAR(50) UNIQUE NOT NULL,
    MATKHAU VARCHAR(255) NOT NULL,
    VAITRO VARCHAR(30) NOT NULL,
    NGAYTAO DATETIME DEFAULT GETDATE(),
    TRANGTHAI BIT DEFAULT 1,
    MANV INT NULL,
    MAKH INT NULL,

    CONSTRAINT FK_TK_NV
    FOREIGN KEY(MANV)
    REFERENCES NHANVIEN(MANV),

    CONSTRAINT FK_TK_KH
    FOREIGN KEY(MAKH)
    REFERENCES KHACHHANG(MAKH),

    CONSTRAINT CHK_TK_USER
    CHECK(
        (MANV IS NOT NULL AND MAKH IS NULL)
        OR
        (MANV IS NULL AND MAKH IS NOT NULL)
    )
)

CREATE TABLE LOAIHANG
(
    MALOAI INT IDENTITY(1,1) PRIMARY KEY,
    TENLOAI NVARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE NHASANXUAT
(
    MANSX INT IDENTITY(1,1) PRIMARY KEY,
    TENNSX NVARCHAR(100) UNIQUE NOT NULL,
    SDT VARCHAR(11),
    EMAIL VARCHAR(100),
    DIACHI NVARCHAR(255)
)

CREATE TABLE HANGHOA
(
    MAHG INT IDENTITY(1,1) PRIMARY KEY,

    TENHG NVARCHAR(255) NOT NULL,

    MOTA NVARCHAR(MAX),

    DVT NVARCHAR(20),

    SOLUONGTON INT DEFAULT 0
    CHECK(SOLUONGTON >= 0),

    GIANHAP DECIMAL(18,2)
    CHECK(GIANHAP >= 0),

    GIABAN DECIMAL(18,2)
    CHECK(GIABAN >= 0),

    HINHANH NVARCHAR(255),

    MALOAI INT NOT NULL,

    MANSX INT NOT NULL,

    NGAYTAO DATETIME DEFAULT GETDATE(),

    NGAYCAPNHAT DATETIME DEFAULT GETDATE(),

    TRANGTHAI BIT DEFAULT 1,

    CONSTRAINT FK_HH_LOAI
    FOREIGN KEY(MALOAI)
    REFERENCES LOAIHANG(MALOAI),

    CONSTRAINT FK_HH_NSX
    FOREIGN KEY(MANSX)
    REFERENCES NHASANXUAT(MANSX)
)

CREATE TABLE HINHSANPHAM
(
    MAHINH INT IDENTITY(1,1) PRIMARY KEY,

    MAHG INT NOT NULL,

    DUONGDAN NVARCHAR(255) NOT NULL,

    CONSTRAINT FK_HSP_HH
    FOREIGN KEY(MAHG)
    REFERENCES HANGHOA(MAHG)
)

CREATE TABLE HOADON
(
    MAHD INT IDENTITY(1,1) PRIMARY KEY,

    NGAYLAP DATETIME DEFAULT GETDATE(),

    TONGTIEN DECIMAL(18,2)
    DEFAULT 0,

    TRANGTHAI NVARCHAR(50),

    PHUONGTHUC_THANHTOAN NVARCHAR(50),

    MAKH INT NOT NULL,

    MANV INT,

    CONSTRAINT FK_HD_KH
    FOREIGN KEY(MAKH)
    REFERENCES KHACHHANG(MAKH),

    CONSTRAINT FK_HD_NV
    FOREIGN KEY(MANV)
    REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CHITIETHD
(
    MAHD INT NOT NULL,

    MAHG INT NOT NULL,

    SOLUONG INT NOT NULL
    CHECK(SOLUONG > 0),

    GIABAN DECIMAL(18,2)
    CHECK(GIABAN >= 0),

    PRIMARY KEY(MAHD, MAHG),

    CONSTRAINT FK_CTHD_HD
    FOREIGN KEY(MAHD)
    REFERENCES HOADON(MAHD),

    CONSTRAINT FK_CTHD_HH
    FOREIGN KEY(MAHG)
    REFERENCES HANGHOA(MAHG)
)

CREATE TABLE NHACUNGCAP
(
    MANCC INT IDENTITY(1,1) PRIMARY KEY,

    TENNCC NVARCHAR(100) NOT NULL,

    SDT VARCHAR(11),

    EMAIL VARCHAR(100),

    DIACHI NVARCHAR(255)
)

CREATE TABLE PHIEUNHAP
(
    MAPN INT IDENTITY(1,1) PRIMARY KEY,

    NGAYNHAP DATETIME DEFAULT GETDATE(),

    TONGTIEN DECIMAL(18,2) DEFAULT 0,

    MANCC INT NOT NULL,

    MANV INT NOT NULL,

    CONSTRAINT FK_PN_NCC
    FOREIGN KEY(MANCC)
    REFERENCES NHACUNGCAP(MANCC),

    CONSTRAINT FK_PN_NV
    FOREIGN KEY(MANV)
    REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CHITIETPN
(
    MAPN INT NOT NULL,

    MAHG INT NOT NULL,

    SOLUONG INT NOT NULL
    CHECK(SOLUONG > 0),

    GIANHAP DECIMAL(18,2)
    CHECK(GIANHAP >= 0),

    PRIMARY KEY(MAPN, MAHG),

    CONSTRAINT FK_CTPN_PN
    FOREIGN KEY(MAPN)
    REFERENCES PHIEUNHAP(MAPN),

    CONSTRAINT FK_CTPN_HH
    FOREIGN KEY(MAHG)
    REFERENCES HANGHOA(MAHG)
)

CREATE TABLE GIOHANG
(
    MAGH INT IDENTITY(1,1) PRIMARY KEY,

    MAKH INT NOT NULL,

    NGAYTAO DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_GH_KH
    FOREIGN KEY(MAKH)
    REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CHITIETGIOHANG
(
    MAGH INT NOT NULL,

    MAHG INT NOT NULL,

    SOLUONG INT DEFAULT 1
    CHECK(SOLUONG > 0),

    PRIMARY KEY(MAGH, MAHG),

    CONSTRAINT FK_CTGH_GH
    FOREIGN KEY(MAGH)
    REFERENCES GIOHANG(MAGH),

    CONSTRAINT FK_CTGH_HH
    FOREIGN KEY(MAHG)
    REFERENCES HANGHOA(MAHG)
)
